config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy

  validates_presence_of :user_id, :text, :group_id
  #validates_presence_ofで値が空でないか検証できる
  after_create :create_feed_content
  #コールバックでfeed_contentsもcreateしている

  def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end
  #find_byメソッドは検索条件に該当したレコードを１件だけ取得するメソッド。findメソッドがidのカラムに対してのみ検索をかけられるのに対し、find_byメソッドは検索条件として複数のカラムを指定できる。今回の例でいうと、answersテーブルからuser_idカラムの値が、引数として渡されている「現在ログインしているユーザーのid」と一致し、かつquestion_idカラムの値が「メソッドを呼び出した元の質問のid」と一致する回答を検索し取得している。
  #question_id: idのidという部分は、self.idのselfを省略した形。

  def answered?(user)
    answers.exists?(user_id: user.id)
  end
  #answered?メソッドでは引数としてユーザーを受け取り、そのユーザーのidがanswersテーブルのuser_idカラムで見つかればtrueを返り値とする。つまり、引数として渡されたuserがその質問に回答しているかどうかを確認できる。

   private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    Question.create(create_params)
    redirect_to :root and return
  end
  #redirect_to :rootを書くだけではアクション内の処理は終了せず次の行のコードを実行していってしまう。今回は下に続く処理がないので問題ないが、慣習的につけるようにした方が良い

  #今まではアクションにQuestion.create(text: create_params[:text], user_id: current_user.id, group_id: current_user.group_id)のようにハッシュのキーと値をそれぞれ書いていた。今回はmergeメソッドを使うことによってストロングパラメーターが生成される際にuser_idとgroup_idのキーと値をもつハッシュを追加する

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end
  #質問への回答を見れるようにするためshowアクションを定義した。インスタンス変数@questionには質問のレコードが１つ入る。トップページから質問個別ページへのリンクを踏んだ際に、パラメーターとして送られる質問のidを利用し、同一の質問のレコードを取得している。@answersには@questionに関係する回答を全て取得し定義している。

  private
  def create_params
    params.require(:question).permit(:text).merge(user_id: current_user.id, group_id: current_user.group_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.erb
<section class="col-md-12">
  <div class="sct_inner">
    <p><%= link_to answer.user.name, user_path(answer.user) %>さんの回答</p>
    <h4><%= answer.text %></h4>
  </div>
</section>

app/views/questions/_question.html.erb
<div class="question_content top_content">
  <header class="question_header">
    <div class="question_image icon_image" style="background-image: url(<%= question.user.avatar.url(:medium) %>);"></div>
    <div class="question_user_info user_info">
      <span><%= link_to question.user.name, user_path(question.user) %></span>
      <time><%= time_ago_in_words question.created_at %></time>
      <%#time_ago_in_wordsは投稿時間を〜時間前のようにしたい場合に利用するビューヘルパーメソッド。特にgemなど入れす利用できる。デフォルトだと英語なのでrailsの環境設定を日本語で表示したい場合はconfig/application.rbの言語設定を日本語(config.i18n.default_local=:ja)にしておく必要がある。また、日本語の文言表示のためにconfig/locales以下にja.ymlを配置しておく%>
    </div>
  </header>
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>
    <div class="questioned">
      <%= link_to "回答#{question.answers.count}件", question_path(question) %>
    </div>
    <% unless question.answers.exists?(user_id: current_user.id) %>
    <%#(question.answers)でアソシエーションを活用し、一つの質問に対して寄せられた回答を全て取得している。さらにその回答中から(.exists?(user_id: current_user.id))で現在ログインしているユーザーが回答したものを探し、存在が確認できなければfalseを返し、回答ボタンを表示する%>
    <%= form_tag(new_answer_path, method: :get, class: "question_submit") do %>
      <%= hidden_field_tag(:question_id, question.id) %>
      <%#hidden_field_tagはユーザーが入力する必要のない自明のデータをパラメーターとして送信したい時利用する。上記では:question_idというキーに対して個別のquestionのidを値として設定している。これによってパラメーターが送られた先では、params[:question_id]とするだけで簡単に対応する質問のidが取得できる%>
      <%= submit_tag("回答する") %>
      <% end %>
      <% else %>
        <div class="answer_other">
          <h4>＊回答済み＊</h4>
        </div>
      <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3><span>Q</span><%= @question.text %></h3>
    <div class="group_action panel-default">
      <div class="panel-body">
        <% unless @question.answers.exists?(user_id: current_user.id) %>
        <%= link_to '質問に回答する', new_answer_path(question_id: @question.id) %>
        <% else %>
        <h4>＊回答済み＊</h4>
        <% end %>
      </div>
    </div>
    <% if @question.answers.present? %>
    <h3><span>A</span>この質問への回答</h3>
    <% if @question.answered?(current_user) %>
    <%= render partial: "questions/answer", collection: @answers %>
    <% else %>
    <h1>＊質問に答えると他の人の回答を見ることができます</h1>
    <% end %>
    <% end %>
  </div>
</div>
<%#「回答する」ボタンの表示に対して条件分岐を設定している。すでにユーザーがその質問に回答していた場合は回答ボタンが表示されず、代わりに「＊回答済み＊」と表示される。
質問個別ページでは、その質問に関係する回答全てを表示する。繰り返し同じ型に当てはめて回答を表示したいため、部分テンプレートを用意する。%>