config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :questions, ->{ order("created_at DESC") }
  has_many :feed_contents, ->{ order("updated_at DESC") }
  #orderオプションは取得する順番を変更できるオプション。全てのオプションの前に記述する。
  #今回モデルで指定したorderオプションは->というlambda(ラムダ)気泡で指定されている。lambdaは匿名関数のことを指し、アソシエーションでオプションを指定する際に用いる。
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(update_params)
  end

  private
  def update_params
    params.require(:group).permit(:key, :detail)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<% provide :title, " | グループ情報編集" %>

<div class="row form">
  <div class="col-lg-12">
    <%= form_for @group do |f| %>
    <h3>グループ名を編集する</h3>
    <div class="form-group">
      <%= f.label :key, :Name, class: "control-label" %>
      <%=f.text_field :key, placeholder: "グループ名を入力してください", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :detail, :Detail, class: "control-label" %>
      <%= f.text_area :detail, placeholder: "グループ概要を入力してください", size: "30x10", class: "form-control" %>
    </div>
    <%= f.submit "送信", class: "btn btn-primary withripple" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide :title, " | #{@group.key}" %>

<div class="row form">
  <div class="col-lg-12">
    <h3><%= @group.key %>
      <small class="edit">
        <%= link_to "編集", edit_group_path(@group) %>
      </small>
    </h3>
    <p><%= @group.detail.blank? ? "このグループの説明はありません" : @group.detail %></p>
    <div class="group_action panel panel-default"></div>
    <h3>Member List</h3>
    <div class="list-group">
      <% @group.users.each do |user| %>
      <div class="list-group-item"><%= link_to user.name, user_path(user) %><hr></div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>グループの編集が完了しました。</h3>
  </div>
</div>