config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_one :feed_content, as: :content, dependent: :destroy
  # ポリモーフィックのアソシエーション。クラス名はfeed_content、ポリモーフィック関連名はcontent。feed_contentのcontent_id、content_typeカラムにanswerのid、answerのタイプ保存されるようにしている。


  validates_presence_of :user_id, :text
  # 値が空でないかのバリデーション


  after_create :create_feed_content
  # 回答がcreateされた後にfeed_contentもcreateされるようコールバックを設定している。
  after_update :update_feed_content
  #回答に変更が加えられたタイミングでもコールバックを設定している。こうすることで編集された投稿がタイムラインの一番上にくるようになる。

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
  end

  def update_feed_content
    self.feed_content.update(updated_at: updated_at)
  end
  #ここでのupdated_atは「self.updated_at」を省略した形で、コールバックが働いた際のレシーバーである回答の更新日時を表す。

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :redirect, only: :new
  #ビューで条件によって表示を分けたことで、一度回答した質問には「回答する」ボタンは表示されなくなった。しかし一度回答した質問であっても直接/answers/new?question_id=1のようなパスにアクセスすることで回答できてしまう。そのためコントローラーで、一度回答したユーザーが直接回答画面にアクセスしてきた際にはホーム画面に遷移するように設定を行う。

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.question_id = @question.id
  end
  #回答を新規登録する際には、その回答に対応するquestionのidも関連づけて保存したいため@answerのプロパティ値としてあらかじめセットしている。
  def create
    @answer = Answer.create(create_params)
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    @answer.update(update_params)
  end

  private
  def create_params
    params.require(:answer).permit(:question_id, :text).merge(user_id: current_user.id)
  end

  def redirect
    if Answer.exists?(question_id: params[:question_id], user_id: current_user.id)
      redirect_to :root
    end
  end

  def update_params
    params.require(:answer).permit(:text)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="answer_content top_content">
  <header class="answer_header">
     <div class="answer_image icon_image" style="background-image: url(<%= answer.user.avatar.url(:medium) %>);"></div>
    <div class="answer_user_info user_info">
      <span><%= link_to answer.user.name, user_path(answer.user) %></span>
      <time><%= time_ago_in_words answer.updated_at %></time>
    </div>
  </header>
  <div class="answer_body">
    <div class="answerd">
      <%= answer.question.user.name %>の質問「<%= link_to answer.question.text, question_path(answer.question) %>」に回答しました。
    </div>
    <% if answer.question.answered?(current_user) %>
    <div class="answer_box">
      <span class="a">A</span>
      <span class="answer_text"><%= answer.text %></span>
      <% if answer.user_id == current_user.id %>
      <small class="edit">
        <%= link_to '編集', edit_answer_path(answer) %>
      </small>
      <% end %>
    </div>
    <% end %>
    <% if answer.question.answers.count > 1 %>
    <div class="answer_other">
      <%= link_to "他#{answer.question.answers.count - 1}件の回答を見る", question_path(answer.question) %>
    </div>
    <% end %>
  </div>
</div>

app/views/answers/create.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>回答の作成が完了しました。</h3>
    <%= link_to "他の人の回答を見る", question_path(@answer.question) %>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/answers/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@answer) do |f| %>
    <h3><span>Q</span><%= @question.text %></h3>
    <div class="form-group">
      <%= f.text_area :text, placeholder: "回答を入力してください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
    </div>
    <%= f.submit "回答する", class:"btn btn-primary withripple" %>
    <% end %>
  </div>
</div>

app/views/answers/new.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@answer) do |f| %>
    <h3><span>Q</span><%= @question.text %></h3>
    <div class="form-group">
      <%= f.text_area :text, placeholder: "回答を入力してください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
    </div>
    <%= f.hidden_field :question_id %>
    <%#ここでもhidden_fieldを用いてユーザーが入力する必要のない自明の値がパラメーターとして設定されている。hidden_fieldをform_forメソッド内で使用する際はf.hidden_field :カラム名、の形で指定する。<input type="hidden" value="2" name="answer[question_id]" id="answer_question_id">のようなhtmlに変換される%>
    <%= f.submit "回答する", class:"btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

app/views/answers/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>質問「<%= @question.text %>」への回答を編集しました。</h3>
     <%= link_to "自分の回答を見る", user_path(current_user) %>
     <%= link_to "ホームに戻る", root_path %>
   </div>
 </div>